Add pdf ocr usage
deepset-ai/haystack-website pull request #140
Opened 2021-09-02 05:22 UTC by shahrukhx01

Based on [OCR PR](https://github.com/deepset-ai/haystack/pull/1349)

2021-09-02 08:19 UTC, shahrukhx01 commented
@PiffPaffM FYI. please review when you’ve time.

2021-09-02 13:32 UTC, PiffPaffM commented on docs/latest/usage/preprocessing.mdx
> +            valid_languages=["deu","eng"])
Is it correct to use "deu" here or does it need to be "de"?

2021-09-02 13:34 UTC, PiffPaffM commented on docs/latest/usage/preprocessing.mdx
> +            Haystack supports extraction of text from images using OCR.
Are there any limitations regarding the file type like jpeg, png, etc. which we need to mention here?

2021-09-02 14:09 UTC, shahrukhx01 commented on docs/latest/usage/preprocessing.mdx
> +            valid_languages=["deu","eng"])
It is "deu" since we are using tesseract, should we also add a link for language codes from tesseract?
https://tesseract-ocr.github.io/tessdoc/Data-Files-in-different-versions.html

2021-09-02 14:10 UTC, shahrukhx01 commented on docs/latest/usage/preprocessing.mdx
> +            Haystack supports extraction of text from images using OCR.
We can add recommended file types like jpeg, jpg, and png, however, there are no limitations mentioned tesseract site.

2021-09-02 15:50 UTC, PiffPaffM commented on docs/latest/usage/preprocessing.mdx
> +            valid_languages=["deu","eng"])
That would be cool. I was a bit confused.

2021-09-02 15:51 UTC, PiffPaffM commented on docs/latest/usage/preprocessing.mdx
> +            Haystack supports extraction of text from images using OCR.
In this case, I would leave it like this. Looks good!

2021-09-02 15:51 UTC, PiffPaffM commented
@shahrukhx01 Thanks for the contribution to our docs! That is great! Looking forward to merging it after these minor changes.

2021-09-02 16:11 UTC, shahrukhx01 commented on docs/latest/usage/preprocessing.mdx
> +            valid_languages=["deu","eng"])
@PiffPaffM I have updated the documentation for this part

2021-09-07 08:04 UTC, shahrukhx01 commented
Hi @PiffPaffM following up on this :)

2021-09-07 21:32 UTC, PiffPaffM approved these changes
LGTM

2021-09-07 21:32 UTC, PiffPaffM commented on docs/latest/usage/preprocessing.mdx
> +            valid_languages=["deu","eng"])
Thanks! The code box for PDF looks a bit weird: https://haystack-website-git-fork-shahrukhx01-a-f7d6bb-deepset-overnice.vercel.app/usage/preprocessing#file-conversion. I think the comment is not interpreted correctly. Can you have a look?

2021-09-08 09:21 UTC, shahrukhx01 commented on docs/latest/usage/preprocessing.mdx
> +            valid_languages=["deu","eng"])
I have changed it into a code comment, but where should we put the link for Tessaract language codes?

2021-09-15 15:23 UTC, brandenchan requested changes

2021-09-15 15:23 UTC, brandenchan commented on docs/latest/usage/preprocessing.mdx
> +            valid_languages=["deu","eng"])
I would suggest you put the link in that same comment. However in the vercel preview, it seems like the import statement is on the same line as the comment. 
https://haystack-website-hv1bt4525-deepset-overnice.vercel.app/usage/preprocessing

2021-09-15 15:23 UTC, brandenchan commented on docs/latest/usage/preprocessing.mdx
> +            valid_languages=["deu","eng"])
Also, we just merged a new branch in that moves this file from `docs/latest/usage/preprocessing.mdx` to `docs/latest/components/preprocessing.mdx`. Could you also make this change so that this PR can be merged?

2021-09-20 16:15 UTC, brandenchan commented
Hi @shahrukhx01, I realise that the restructuring of the repo might have made this PR a little tricky to finish off. Would it be alright if I incorporate your changes into another PR of mine (#164)? This will save the effort of rebasing / merging branches. We will of course credit your work in the new PR :)

2021-09-20 16:17 UTC, shahrukhx01 commented
@brandenchan yes definitely no problem.

2021-09-21 08:02 UTC, closed without merging