Update Docs around AzureConverter
deepset-ai/haystack-website pull request #206
Opened 2021-11-30 16:05 UTC by tholor

Preprocessing Guide:
- Adds Azure + Markdown file converters
- Adjusts description of formats

Table QA Guide: 
- Link Azure Converter

2021-11-30 16:46 UTC, tholor commented
@brandenchan I somehow could not access the preprocessing page in the vercel preview. Do you see why this might be broken?

2021-12-01 13:49 UTC, brandenchan requested changes

2021-12-01 13:49 UTC, brandenchan commented on docs/latest/components/preprocessing.mdx
> +        'content': DOCUMENT_TEXT_HERE,
This syntax doesn't look right to me - guessing you copied it from the dictionary example?

2021-12-01 13:49 UTC, brandenchan commented on docs/latest/components/preprocessing.mdx
> +You can index `Document` objects or plain dictionaries to a Haystack `DocumentStore`. Therefore, the output of your preprocessing should comply to one of these two formats (we recommend `Document`, s
I think we should simplify the wording and punctuation here. My suggestion
"""
You can index `Document` objects (recommended) or plain dictionaries into a Haystack `DocumentStore`. 
The output of your preprocessing should comply with one of these two formats.
To learn more about the `Document` class see [Primitives](/components/primitives).
"""

2021-12-01 13:49 UTC, brandenchan commented on docs/latest/guides/table_qa.mdx
> +If you have your tables embedded in raw files (e.g. within a PDF), you can use the `AzureConverter` to parse them into the required format (see [File Conversion](/preprocessing#file-conversion)).
Visually I think this will be much nicer if we wrap it in a highlight box - see lines 6-10 of this file

2021-12-01 17:16 UTC, tholor commented on docs/latest/components/preprocessing.mdx
> +        'content': DOCUMENT_TEXT_HERE,
Good catch! copy&paste bug :)

2021-12-01 17:21 UTC, tholor commented on docs/latest/guides/table_qa.mdx
> +If you have your tables embedded in raw files (e.g. within a PDF), you can use the `AzureConverter` to parse them into the required format (see [File Conversion](/preprocessing#file-conversion)).
I personally really don't like the current design of these highlight boxes. Their width doesn't fit the code boxes or paragraphs and the coloring looks quite distracting (especially in the dark mode): 

![image](https://user-images.githubusercontent.com/1563902/144282466-b0c38bfa-f874-4ca8-bc9c-1f16be4564b8.png)

I would therefore keep it as regular text for now. Let's improve the design of these highlight boxes soon and then use them in more places.

2021-12-01 17:27 UTC, tholor commented on docs/latest/components/preprocessing.mdx
> +You can index `Document` objects or plain dictionaries to a Haystack `DocumentStore`. Therefore, the output of your preprocessing should comply to one of these two formats (we recommend `Document`, s
Done

2021-12-01 17:27 UTC, tholor commented on docs/latest/components/preprocessing.mdx
> +        'content': DOCUMENT_TEXT_HERE,
Fixed

2021-12-02 09:25 UTC, brandenchan approved these changes

2021-12-02 09:31 UTC, merged