Added model distillation guide
deepset-ai/haystack-website pull request #213
Opened 2021-12-07 14:30 UTC by MichelBartels

This adds a guide describing how and why to use model distillation. It also contains a table listing the performance improvements of model distillation for different models.

2021-12-07 15:04 UTC, julian-risch requested changes
Hi @MichelBartels the text looks already quite good to me. Just left some minor comments also to make sure that this guide is similar to the other ones we already have.
Regarding the table I am still a bit unsure what columns to include or whether to change rows with columns. Maybe we could also split it in two tables, for example, one with F1 score and one with exact match. I am afraid that the table is too large at the moment.

2021-12-07 15:04 UTC, julian-risch commented on docs/latest/guides/model_distillation.mdx
> +| prajjwal1/bert-medium | deepset/bert-large-uncased-whole-word-masking-squad2 | SQuADv2 | 5.0 | 1.0 | 68.6% | 72.8% | 65.6% | 69.6% | 78.9% | 83.2%7
I see that the table already has many columns. However, one thing that's currently missing but important is the name (with a link to the model hub page) of the distilled model. Please add these names and links.

2021-12-07 15:04 UTC, julian-risch commented on docs/latest/guides/model_distillation.mdx
> +Here are the results of some of our test and the parameters used:
Maybe "some of our test" -> "some of our tests"? Maybe we can stress here something like: "We are actively working on extending model distillation features in haystack. The following table shows experiment results of the first version of model distillation in haystack. Stay tuned for updates!"

2021-12-07 15:04 UTC, julian-risch commented on docs/latest/guides/model_distillation.mdx
> +# Model distillation
Let's capitalize this headline and also the other headlines as in the other guides on the documentation website. Here: "Model Distillation"

2021-12-07 15:04 UTC, julian-risch commented on docs/latest/guides/model_distillation.mdx
> +In most cases, a larger model size leads to better performance. But the more parameters a model has, the more resource-intensive it is. This makes deployment more difficult and increases latency.
Let's replace "performance" with "result quality" to disambiguate here. It's not about runtime, for example.

2021-12-07 15:04 UTC, julian-risch commented on docs/latest/guides/model_distillation.mdx
> +For this reason, choosing the right reader is always a trade-off between performance and deployment cost. Model distillation is one way to bridge the performance gap between a large language model (t
Let's replace "performance" with "result quality" here too.

2021-12-07 15:04 UTC, julian-risch commented on docs/latest/guides/model_distillation.mdx
> +Most times, you should set this to a relatively high value (e.g. 0.75).
Please add here two sentences on what the extreme values mean (0 and 1). I think it helps users understanding the parameter, explains that we don't always need labels for model distillation and also thereby mentions the range of this parameter (between 0 and 1).

2021-12-07 15:08 UTC, julian-risch commented
Maybe we could also add a sentence to explain that the current model distillation method that we are using aims to improve the result quality of small models. In contrast, pruning techniques would try to make an existing model smaller by keeping the same result quality. I liked your "bridging the gap" sentence here! 👍 Maybe we can elaborate a bit more there. Users might have heard about model distillation or distilled models somewhere else and it could be that they are expecting something else than what we provide.

2021-12-07 16:45 UTC, brandenchan commented
Cool to see this in action! Thanks for your work on distillation and also on documenting it. Just want to let you know that to make this page show on the website you will need to add an entry into ` haystack-website/docs/latest/menu.json` - this file defines what will appear on the left Table of Contents.

2021-12-08 16:56 UTC, MichelBartels commented on docs/latest/guides/model_distillation.mdx
> +| prajjwal1/bert-medium | deepset/bert-large-uncased-whole-word-masking-squad2 | SQuADv2 | 5.0 | 1.0 | 68.6% | 72.8% | 65.6% | 69.6% | 78.9% | 83.2%7
I have added the links now.

2021-12-08 16:57 UTC, MichelBartels commented on docs/latest/guides/model_distillation.mdx
> +Here are the results of some of our test and the parameters used:
Okay, that first one was a typo. I added the second part.

2021-12-08 16:57 UTC, MichelBartels commented on docs/latest/guides/model_distillation.mdx
> +# Model distillation
Okay, I have changed that.

2021-12-08 16:59 UTC, MichelBartels commented on docs/latest/guides/model_distillation.mdx
> +In most cases, a larger model size leads to better performance. But the more parameters a model has, the more resource-intensive it is. This makes deployment more difficult and increases latency.
I replaced it with quality of results and accuracy. I hope that's also okay.

2021-12-08 16:59 UTC, MichelBartels commented on docs/latest/guides/model_distillation.mdx
> +For this reason, choosing the right reader is always a trade-off between performance and deployment cost. Model distillation is one way to bridge the performance gap between a large language model (t
Please see answer above.

2021-12-08 17:00 UTC, MichelBartels commented on docs/latest/guides/model_distillation.mdx
> +Most times, you should set this to a relatively high value (e.g. 0.75).
Okay, I have added a few sentences explaining that.

2021-12-08 17:01 UTC, MichelBartels commented
I have now added a sentence referring to pruning. I also split the table into two. One for the parameters and one for the results.

2021-12-08 17:02 UTC, julian-risch commented
Then what's left is mainly editing the `haystack-website/docs/latest/menu.json` file

2021-12-08 17:02 UTC, MichelBartels commented on docs/latest/guides/model_distillation.mdx
> +| prajjwal1/bert-medium | deepset/bert-large-uncased-whole-word-masking-squad2 | SQuADv2 | 5.0 | 1.0 | 68.6% | 72.8% | 65.6% | 69.6% | 78.9% | 83.2%7
The first link is not yet working as I am still working on the model upload. I will write an update message later when it's finished.

2021-12-08 17:13 UTC, MichelBartels commented
I have now updated the menu.json. However, I am not entirely certain I did this correctly. I have added an entry smilarly to the other guides, but haven't specified the filename. I am not sure where I have to add that.

2021-12-08 18:22 UTC, MichelBartels commented on docs/latest/guides/model_distillation.mdx
> +| prajjwal1/bert-medium | deepset/bert-large-uncased-whole-word-masking-squad2 | SQuADv2 | 5.0 | 1.0 | 68.6% | 72.8% | 65.6% | 69.6% | 78.9% | 83.2%7
All models are uploaded now.

2021-12-13 10:24 UTC, MichelBartels commented
Currently, the guide isn't shown in the sidebar. Also, despite working in the Github preview the table isn't correctly rendered. I am not quite sure what is causing those issues

@brandenchan Could you help with this?

2021-12-13 16:48 UTC, julian-risch commented on docs/latest/menu.json
> +      {"slug": "model-distillation", "title": "Model Distillation"},
@MichelBartels The last comma here behind `"Model Distillation"}` could be a problem, I think.

2021-12-13 16:57 UTC, MichelBartels commented on docs/latest/menu.json
> +      {"slug": "model-distillation", "title": "Model Distillation"},
I have now changed this line. This would make sense as trailing commas aren't part of the JSON specification.

2021-12-13 17:08 UTC, julian-risch approved these changes
Let's wait with merging until the preview in vercel looks good.

2021-12-14 16:54 UTC, merged