Review the Model Distillation guide
deepset-ai/haystack-website pull request #265
Opened 2022-03-09 09:06 UTC by agnieszka-m

Review of the model distillation guide which includes simplifying the language whenever possible and formatting changes. It's a WIP.

2022-03-09 15:35 UTC, brandenchan requested changes

2022-03-09 15:35 UTC, brandenchan commented on docs/latest/guides/model_distillation.mdx
> +The optional intermediate layer distillation step requires a lot of data. Because acquiring a lot of training data is expensive, the TinyBERT paper suggests a data augmentation approach in which you
Let's capitalize Haystack

2022-03-09 15:35 UTC, brandenchan commented on docs/latest/guides/model_distillation.mdx
> +The following paragraphs are only relevant for intermediate layer distillation. To use prediction layer distillation, jump directly to "Prediction layer distillation". Otherwise, read on to learn how
I don't think I am so in favor of saying "the following paragraphs are only relevant..." because it is not clear how far that extends exactly. Also jump directly to X implies that users are reading beginning to end.

2022-03-09 15:35 UTC, brandenchan commented on docs/latest/guides/model_distillation.mdx
> +`distil_intermediate_layers_from` accepts all the parameters you can use for training. You must provide all the necessary parameters in this method. The method also accepts additional parameters like
I think a link to the API reference here is better than talking about parameters in text

2022-03-09 15:35 UTC, brandenchan commented on docs/latest/guides/model_distillation.mdx
> +When using intermediate layer distillation, we recommend using the default parameters. You can try tuning the distillation-specific parameter `temperature` and adjusting all the parameters that are r
I think a link to the API reference here is better than talking about parameters in text

2022-03-09 15:35 UTC, brandenchan commented on docs/latest/guides/model_distillation.mdx
> +<table>
We can shorted some of the model names but keep the specific links. It will be visually better

2022-03-09 15:35 UTC, brandenchan commented on docs/latest/guides/model_distillation.mdx
> +<table>
We can shorted some of the model names but keep the specific links. It will be visually better

2022-03-10 10:38 UTC, agnieszka-m commented on docs/latest/guides/model_distillation.mdx
> +The optional intermediate layer distillation step requires a lot of data. Because acquiring a lot of training data is expensive, the TinyBERT paper suggests a data augmentation approach in which you
Done

2022-03-10 10:40 UTC, agnieszka-m commented on docs/latest/guides/model_distillation.mdx
> +The following paragraphs are only relevant for intermediate layer distillation. To use prediction layer distillation, jump directly to "Prediction layer distillation". Otherwise, read on to learn how
Yeah, I also had trouble how to solve that, in the end I decided to leave as is. The resolution to me would be grouping all intermediate layer distillation and by using good headers let users know that it's for intermediate layer distillation only and then delete this text. I don't think I understand this topic enough to be able to do that now.

2022-03-10 10:45 UTC, agnieszka-m commented on docs/latest/guides/model_distillation.mdx
> +`distil_intermediate_layers_from` accepts all the parameters you can use for training. You must provide all the necessary parameters in this method. The method also accepts additional parameters like
Do you have any particular API in mind or just the reference section? Sure, we can add a link but I think having these params described here is fine in case it's enough for somebody and then they don't have to go anywhere else for ht einformation

2022-03-10 10:49 UTC, agnieszka-m commented on docs/latest/guides/model_distillation.mdx
> +<table>
I'm wondering about this one. It will surely be better visually but won't it cause some kind of problems for the users? let's assume they don't click the link but want to find the models themselves or something. I'm not sure.

2022-03-11 14:55 UTC, brandenchan commented on docs/latest/guides/model_distillation.mdx
> +The following paragraphs are only relevant for intermediate layer distillation. To use prediction layer distillation, jump directly to "Prediction layer distillation". Otherwise, read on to learn how
Ok that's fine - let's leave that out of scope for now but maybe revisit it down the line

2022-03-11 14:55 UTC, brandenchan commented on docs/latest/guides/model_distillation.mdx
> +`distil_intermediate_layers_from` accepts all the parameters you can use for training. You must provide all the necessary parameters in this method. The method also accepts additional parameters like
Actually, I realise that the API docs are not yet included, and also API is not yet in a state where I want people to be relying on it I guess. Let's leave as is then

2022-03-11 14:59 UTC, brandenchan commented on docs/latest/guides/model_distillation.mdx
> +<table>
I guess I think the user will click on the link because that would be more straightforward than copying the name and putting it into a google search. Let me take care of this in a separate PR

2022-03-11 14:59 UTC, brandenchan approved these changes

2022-03-14 12:30 UTC, merged