Refactor nodes pages
deepset-ai/haystack-website pull request #278
Opened 2022-04-14 14:51 UTC by brandenchan

2022-04-15 15:00 UTC, TuanaCelik commented
The directory name in `[..slug]... `had to be fixed + a destination and source duo added to the `next.config.js` :) - Should be working now

2022-04-26 08:27 UTC, agnieszka-m requested changes
I think it's much more useful now with the table at the beginning that lets you quickly check how to use the node. One thing I have a problem with is the Usage section, I'm not sure it belongs here or to the API? if it belongs here then we'll need to explain all the arguments here as well. I think we should also ask Tuana about this, maybe she'll have some thoughts.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +Some perform steps like preprocessing, retrieving or summarizing text
retrieving, or (missing comma)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +while route queries through different branches of a Pipeline.
while routing

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
>  Nodes are chained together using a [Pipeline](/components/pipelines).
maybe also add info that nodes work like building blocks, you can replace one with the other or delete them, etc. Also, I'd add some info that when nodes are in a pipeline, a node takes the output of the previous node as input and processes it. It may seem obvious but I think that it's not, especially to someone new to nlp.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
I'd delete this whole paragraph. This is a page where you come to see what nodes are available and what they do. I'd move the info about run methods and how they're run in a pipeline to the Pipeline page.

Here maybe we can say something like: Nodes are designed to be used within a Pipeline but you can also call each node outside of it. For more information on what methods you can call, see the node's documentation.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [FileConverters](/pipeline_nodes/file-converters)      | PDFToTextConverter, DocxToTextConverter, AzureConverter, ImageToTextConverter, MarkdownConverter | Performs cleaning and splitting on Docume
In the "Classes" column, I'd put each node in a new line for better readability.(just using line break).

Also, should be "Perform", not "performs" as it's File Converters. Should we also add info that they convert different file formats to text? and that it's best to use them at the beginning of the pipeline?

I think text converter is missing

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [PreProcessor](/pipeline_nodes/preprocessor)      | PreProcessor                                 | Performs cleaning and splitting on Documents   |
It has the same description as file converters so may be confusing. Also, to me it was unclear why I'd need this component at all so maybe it's worth mentioning that it's useful for long documents

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [Retriever](/pipeline_nodes/retriever)       | BM25Retriever, ElasticsearchRetriever, DensePassageRetriever, TableTextRetriever, EmbeddingRetriever, TfidfRetriever, ElasticsearchFilterOnlyRetriever
I'd reformat the Classes column to have one class per line (it would be best to just use unordered list but, well, docs as code..). 
I'd rephrase the description: Fetches the documents that are relevant to the query from the document store assigned (? can we use assigned? coupled seems unclear here) to it

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [Reader](/pipeline_nodes/retriever)      | FARMReader, TransformersReader                      |  Finds an answer to a question by selecting a text span in the provided Documents |
can we just say "... by highlighting it in the passage of text"? I think it would be easier to understand for nlp beginners. When we say "provided Documents", I think we'd need to explain who/what provides the documents, etc.. Also, here, they might not know what documents are.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [Generator](/pipeline_nodes/generator)      | RAGenerator, Seq2SeqGenerator  |  Generates an answer to a question by reading through the provided documents and composing an answer word-by-word |
should Documents have a capital D?
Maybe instead of "provided documents" just "Documents"? It's unclear who provides them..

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [Summarizer](/pipeline_nodes/summarizer)      | TransformersSummarizer  |  Creates a shorter overview of a given Document |
delete "given"

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [Translator](/pipeline_nodes/translator)      | TransformersTranslator  |  Translate text from one language into another |
Translates

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [Ranker](/pipeline_nodes/ranker)      | SentenceTransformersRanker  |  Reorders a set of Documents based on their relevance to the Query |
Should it be "Orders"?

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [Query Classifier](/pipeline_nodes/query-classifier)      | TransformersQueryClassifier, SklearnQueryClassifier  |  Distinguishes between queries that are keywords, questions or statements and rout
Maybe rephrase to: Recognizes the query type and routes it to the correct branch of the Pipeline.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [Question Generator](/pipeline_nodes/question-generator)      | QuestionGenerator  | takes a Document as input and generates questions which it believes can be answered by the Document |
Takes (capital T)

I'd rephrase: Takes a Document as input and generates questions that this Document can answer.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [Document Classifier](/pipeline_nodes/document-classifier)      | TransformersDocumentClassifier  |  Performs classification on Documents and attaches it as metadata |
I'd rephrase to make it clearer: Classifies Documents and attaches the classification outcome as the Document metadata.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [Route Documents](/pipeline_nodes/route-documents)      | RouteDocuments  |  Routes documents based on their content type or a metadata field  |
Routes documents to appropriate Pipeline branches based on..

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [Join Documents](/pipeline_nodes/join-documents)      | JoinDocuments  |  Takes Documents from multiple Nodes and joins them to form one list of Documents. |
delete full stop (for consistency)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
>  ## Custom Nodes
See my comment above, I'd move this whole section to a separate topic called Creating Custom Nodes.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +## Available Nodes
Here I'd add something like: These are the ready-made nodes that you can add to your Haystack pipelines. You can also create your own nodes. For more information on how to do it, see Creating Custom Nodes (and here a link to a topic on custom nodes)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +The PreProcessor can perform different kinds of preprocessing on a `Document`:
How about: Use PreProcessor to normalize white spaces, get rid of header and footer, clean empty lines in your Documents, or split them into smaller pieces.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +Splitting is generally recommended where long `Document`s are involved
I'd delete the code formatting for Documents, it's really difficult to read the way it is now

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +since this can improve the performance of retrieval
I'd rephrase: Splitting is generally recommended for long Documents as it makes the Retriever's job easier and speeds up Question Answering.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +For suggestions on how best to split your documents, see [Optimization](/guides/optimization)
missing full stop

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +
I'd add info: Here's how you can initialize PreProcessor on its own:

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +from haystack.nodes import PreProcessor
shall we add a comment here saying tha tyou first need to import it from haystack nodes?

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +doc = converter.convert(file_path=file, meta=None)
can we just use doc = file_path? adding a converter here is confusing I think

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +processor = PreProcessor(
how about adding a comment for each of these parameters explaining what it does?

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +
I'd reformat the arguments into a table with the following columns: Argument, Type, Possible values, Description

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +- `clean_empty_lines` will normalize 3 or more consecutive empty lines to be just a two empty lines
will normalize => normalizes three or more consecutive empty lines so that they become two empty lines (?? it's totally unclear to me why two empty lines are better than three empty lines?)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +- `clean_whitespace` will remove any whitespace at the beginning or end of each line in the text
will remove => removes

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +- `clean_header_footer` will remove any long header or footer texts that are repeated on each page
will remove -> removes

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +- `split_by` determines what unit the document is split by: `'word'`, `'sentence'` or `'passage'`
by. Possible values:
- word
- sentence
- passage - here I'd explain what a passage is, how long it is, etc as it's unclear

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +- `split_overlap` sets the amount of overlap between two adjacent documents after a split. Setting this to a positive number essentially enables the sliding window approach.
I think this parameter needs more explanation, what happens if I set it to -5, what happens if I set it to -15? or to 5 vs 15?

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +## Document Format
should this information be added to "Input" in the table at the beginning?
Input: Document (can take a Haystack `Document` object or a plain dictionary)
And in this section:
# Usage
- This is how you initialize PreProcessor with a Document Object [here code sample]
- This is how you pass a dictionary to PreProcessor instead of a plain Document object: [here the code sample]

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_converters.mdx
> +There are a range of different file converters in Haystack that
How about: Use file converters to extract text from documents in different formats and and cast it into the unified Document format.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_converters.mdx
> +|__Input__       | Files                                                                                                                                                                  |
can we add a link to an explanation what a file is?

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_converters.mdx
> +|__Classes__     | PDFToTextConverter, DocxToTextConverter, AzureConverter, ImageToTextConverter, MarkdownConverter
put each class in a new line

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_converters.mdx
> +**Tutorial:** Check out our [advanced indexing tutorial](/tutorials/doc-class-index) for an example on how
I'd put the reason first: To see an example of file converters in a pipeline, see out advanced indexing tutorial

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_converters.mdx
> +## Usage
I'm missing an explanation of what each of these converters do.  A section like Available Converters and info or a table like:
| --- | --- |
| Use.. | To.. |
|PDFToTextConverter | Convert PDF files to text |
or a smiple list explaining what document formats you can convert using which converters

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_converters.mdx
> +
Click a tab to see how to initialize each converter

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_converters.mdx
> +          <code>from haystack.nodes import PDFToTextConverter</code>
add comments to the code, explain thta you first need to import the converter, if you're using parameters, explain what they do, etc.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_converters.mdx
> +Haystack also has a `convert_files_to_dicts()` utility function that
I don't think this information belongs here. We have to think about when a user would need/use this function and add this explanation there.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/crawler.mdx
> +In Haystack, you will find a web crawler that will help you scrape text from websites and save it to file.
I'd replace this description with an explanation why you'd need to use it, for example, you can use crawler if you want to add the contents of a website to your files to use them for search. Crawler scrapes the text from a web site and saves it to a file.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/crawler.mdx
> +|__Input__       | Files                                                                                                                                                                  |
add a link to an explanation of what files are in haystack

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/crawler.mdx
> +## Usage
To initialize crawler, run:

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/crawler.mdx
> +from haystack.nodes import Crawler
add comments to code explaining that first you need to import it, then explain what each parameter does.

Also, I noticed that some nodes have arguments explain in the usage section, some don't.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/crawler.mdx
> +## Example Script
Example Script -> An Example of a Pipeline Using Crawler

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
> +The Retriever can perform Document Retrieval by sweeping through a document store and returning a set of candidate documents that are relevant to the query.
can perform -> performs

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
> +saving the Reader from doing more work than it needs to and speeding up the querying process.
missing comma after needs to

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
> +The Retriever is tightly coupled with the Document Store and requires a Document Store object in its initialization.
..with the document store. You must specify a document store when initializing the Retriever. 

Btw. document store is sometimes written in capital letters, sometimes not. What's the right way?

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
> +When it is run, the Retriever receives a Query as input, which it uses to query into the documents contained in the Document Store,
When it is run - > do you mean Retriever or document store? Can we make it active voice - > When the document store runs, the Retriever receives a Query as input. (I'd also split it into shorter sentences). It then uses the Query to check the documents stored in the document store and pass the best candidates on (.. to the Reader?).

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
> +|__Classes__     | BM25Retriever, ElasticsearchRetriever, DensePassageRetriever, TableTextRetriever, EmbeddingRetriever, TfidfRetriever, ElasticsearchFilterOnlyRetriever
one class per line

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
Here, I'd add a section:
# Available Retrievers
## TableTextRetriever
## BM25
## EmbeddingRetriever
.. and all other available retrievers, I think not all of them are documented right now so this would need to be updated (for example, there's Text2SparqlRetriever which is not documented anywhere I think)
In each of these section, there would need to be a description of what this retriever does and when it's best to use it, and also what document stores it's compatible with.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
> +Our starting recommendations would be to use an Embedding Retriever if GPU acceleration is available,
If you're unsure which retriever to use, see the sections below explaining each retriever type (assuming that we add these sections :). 
Our starting recommendations are to use an EmbeddingRetriever if you can use GPU acceleration. If you can't use GPU, we recommend the BM25 retriever.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
> +Have a read of the sections below to learn about different types of Retrievers.
Even before the Available REtrievers section, I'd add a section Dense and Sparse retrievers with a table that compares the two  types

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
I'd add a list: 
- To initialize a Retriever, pass a document store as its argument: <code>
- To run a Retriever on its own, use the retrieve() method. It returns a list of Document objects: <code>
- To run a Retriever within a ready-made pipeline, run: <code>

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
I'd move Document Store Compatibility to a separate section, probably after all the sections with types of retrievers. It also needs to be updated, there are retrievers and document stores missing here.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
> +BM25 is a variant of [TF-IDF](https://haystack.deepset.ai/pipeline_nodes/retriever#tf-idf) that we recommend you use if you are looking for a retrieval method that does not need a neural network for
Use BM25 if you are looking for a retrieval method that doesn't need a neural network for indexing. BM25 is a variant of TF-IDF but it's better in two main aspects:

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
>  - It saturates `tf` after a set number of occurrences of the given term in the document
Not sure why this code is here all of a sudden. It needs some intro and comments in the code

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/retriever.mdx
>  # Retriever
This topic needs a lot of reorg, see farther comments. We need to rething the "Usage" section I think. So here, if we want to keep it, I think it needs to be there in each section for a retriever type.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
> +The Reader takes a question and a set of Documents as input and returns an Answer
Use a Reader if you want your answers highlighted. The Reader takes a question...

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
> +The Reader, is also known as an Open-Domain QA systems in Machine Learning speak.
no need for comma, systems ->system

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
> +- Require a GPU to run quickly
Requires

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
> +
Here I'd add a section Farm vs Transformers Readers and explain the differences between them.

Then, I'd have a section called 
# Available Readers
and within that:
## FARMReader
## Transformers Reader

then another section called
# Models

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
> +## Usage
again, I'm not sure where this should go but it should definately be a list:
- To initialize a reader, run: <code>
- To run a reader on its own, use the predict() method: <code>
 It returns a dictionary: <code>
 - if you want to set up Haystack as a service, use the REader in a pipeline: <code>
-

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
First, explain what a model is and that a reader needs it.
Tell them that there's a place where models are stored called HF and that they can find a lot of ready models there, maybe give them the URL where our models are stored. Then tell them it's enough to just add the hub name and the reader will use the model directly from HF.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
> +The loading of model weights is handled by Haystack.
Can we say it simpler? I'm not sure everyone knows what "model weights" are

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
> +Here are our recommendations for models to start with:
If you're unsure which model to use, here are our recommendations that you can start with:

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
> +            <p>A well rounded model and our recommended starting point.</p>
well-rounded

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
>  <Tabs
I'd change tab titles to Models for FARM Reader/Models for Transformers Reader

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
>  ## Fine-tuning, Saving, Loading and Converting
The information here is a bit chaotic. Should it be in a separate topic called Fine-tuning a model? I don't know

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
>  Simply call the `train()` method to kick off training.
To kick off training, call the train() method.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
>  This method will also save your model in the specified save directory.
This method saves..
Ok, so we're letting them know there's this method but we're not giving them any concrete info how to use it. What are the arguments? what do they mean? what are the possible values?

The code below should have comments explaining what the parameters mean.

Also, I do'nt know what this means: If you want to load the model at a later point, simply initialize a `FARMReader` object as follows.
What is the "later point"? after I fine tune it? Can I also use it with a Transformers Reader or does it need to be FARMReader?
Maybe thsi should say: After you fine tuned your model, you can pass it to a reader: here a code sample how to do it. 

Maybe this section should be like: h1. Models h2. Fine Tuning a Model h2 Converting a Model Into HF Format

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
>  ## Confidence Scores
This might need to be a topic on its own. Here, the user is trying to find out how to use Reader and confidence scores come after they've already figured it out and probably used it in a pipeline.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/generator.mdx
>  as well as passages provided to it with a retriever (non-parametric memory).
as well as -> and

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/generator.mdx
>  as well as passages provided to it with a retriever (non-parametric memory).
retriever -> Retriever

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/generator.mdx
>  With the advent of Transformer based retrieval methods such as [Dense Passage Retrieval](https://arxiv.org/abs/2004.04906),
transformer-based (any reason transformer should be capitalized?)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/generator.mdx
>  retriever and generator can be trained concurrently from the one loss signal.
Retriever and Generator

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/generator.mdx
delete full stops in the lists

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/generator.mdx
> +**Tutorial:** Checkout our tutorial notebooks for a guide on how to build your own generative QA system with [RAG](/tutorials/retrieval-augmented-generation)
Build your own generative QA system with RAG and LFQA.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/generator.mdx
>  ## Usage
- To initialize a Generator, run:
- To run a Generator in a pipeline, run:
- To run a stand-alone Generator, run:

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/summarizer.mdx
> +The Summmarizer is a useful tool for getting a short overview of a Document that is otherwise quite long.
Use a Summarizer if you need a short overview of a long Document.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/summarizer.mdx
> +Using the Summarizer, you could, for example, gain a more manageable glimpse into what Documents your Retriever is returning.
Summarizer can give you a glimpse of what Documents your Retriever is returning.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/summarizer.mdx
> +You can use any summarization model from HuggingFace Transformers by providing the model name.
Summarizer requires a summarization model. You can use the models stored in Hugging Face, just provide the model name when initializing the Summarizer.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/summarizer.mdx
>  See the up-to-date list of available models [here](https://huggingface.co/models?filter=summarization).
"here" -> Hugging Face

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/summarizer.mdx
> +
add comments to the code, say explicitly what each code snippet does:
- to initialize the Summarizer, run:
the output is the summarization and original document text:
- to use a Summarizer in a pipeline, run:

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/translator.mdx
> +For a list of compatible models, see the HuggingFace [Model Hub](https://huggingface.co/models?pipeline_tag=translation&sort=downloads).
Translator requires a language model. For a list..

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/translator.mdx
> +## Use Case: Wrapping another Pipeline
I'd say: Example: Using a Translator in a Pipeline

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/translator.mdx
> +You can use a `Translator` node in your pipeline to
to:

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/translator.mdx
> +## Use Case: Wrapping another Pipeline
Ah ok, its uses the wrapperpipeline but it doesn't explain what it is or what it does or how to use it... it also doesn't explain that it uses a ready-made pipeline.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/ranker.mdx
> +They are particularly useful when your Retriever has high recall but poor relevance scoring.
They are -> It is (because we're talking about Ranker here, right?)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/ranker.mdx
> +models powered by transformers meaning that they are sensitive to word order and syntax.
comma after transformers

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/ranker.mdx
> +In Haystack, you can use any [Cross-Encoder](https://huggingface.co/cross-encoder) model that returns as a single logit
delete "as" after "returns"

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/ranker.mdx
> +## Usage
so here we're missing the info that's ther ein the Usage section for other nodes: how to initialize, how to run it on its own

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/ranker.mdx
> +To use it in a Pipeline:
To use the Ranker in a pipeline:

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/ranker.mdx
> +The `SentenceTransformersRanker` can also be used in isolation by calling its `predict()` method after initialization.
To use the `SentenceTransformersRanker1` outside of a pipeline, call predict(): (here a code sample)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/ranker.mdx
> +While the BM25 retriever is fast and light weight, it is not sensitive to word order but rather treats text as a bag of words.
lightweight

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/ranker.mdx
> +The `SentenceTransformersRanker` has a `train()` method to allow for this training.
should we add an example how to use this method? also explain the arguments it takes, etc.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
> +The Query Classifiers in Haystack distinguish between three different classes of queries:
you can get rid of "different", it's redundant

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
> +Based on its classification, it can route the query to a specified branch of the Pipeline.
Based on this classification, the Query Classifier routes the query..

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
> +By passing on queries to Nodes that are more suited to that kind of query, you can expect to get better search results.
Passing on queries to Nodes that are more suited to handle them, you get better search results.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
> +For example, the Dense Passage Retriever is trained on full questions and so it makes sense to only pass questions to it.
... so it works best if you only pass questions to it.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
> +By choosing also to pass keyword queries to a BM25 retriever, such as the ElasticsearchRetriever,
Passing keyword queries to a BM25 Retriever (capital R)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
> +you can reduce the load on the GPU powered Dense Passage Rertriever.
GPU-powered

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
> +## Usage (Standalone)
let's align the formatting here to the other node topics:
# Usage
- To use Query Classifier as a standalone node, run: 
The node returns two objects:.. You can use this information in a pipeline for routing the query to the next node.
- To use Query Classifier in a pipeline, run:

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
Maybe under the table, we could add info that this is a decision node, etc. Basically the paragraph and diagram that's currently under Usage (Pipeline)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
> +## Query Types
I'd move it to the top, as the first section below the table

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
> +Query Classifier models should be able to make its prediction separate from the presence or absence of the question mark.
A Query Classifier should be able to classify a query regardless of whether it ends with a question mark or not.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
> +These queries consist also of a regular, grammatical sentences.
This type of query is a declarative sentence, such as:

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/query_classifier.mdx
> +Pass your own `Transformer` binary classification model from file or use one of the following pretrained models hosted on Huggingface:
Hugging Face

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/question_generator.mdx
> +|__Position in a Pipeline__| At the very beginning of an querying Pipeline |
an -> a

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/question_generator.mdx
> +## Usage
add a comment what this code does - it runs the QG as a standalone node? can we also add info how to initialize it and run it in a pipeline?

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/document_classifier.mdx
> +The Document Classifier Node is a transformer based classification model used to create predictions that are attached to documents as metadata.
This node is a transformer-based classification model that makes predictions which it then attaches to Documents as metadata. 

one question - this node is a model? or does it use a model?

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/document_classifier.mdx
>  For example, by using a sentiment model, you can label each document as being either positive or negative in sentiment.
..by using a sentiment model with Document Classifier, you can label each Document as positive or negative in sentiment.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/document_classifier.mdx
>  Through a tight integration with the HuggingFace model hub, you can easily load any classification model by simply supplying the model name.
HuggingFace -> Hugging Face (we need to be careful to correctly write their name..)

by simply supplying -> by supplying

Or we can simplify it: Thanks to tight integration with the Hugging Face model hub, you can supply a model name to load it.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/document_classifier.mdx
> +**Note: ** The **Document Classifier is different from the Query Classifier.**
typically, emphasis is done through italics, not bold.

Maybe we can add here that the query classifier it a decision node while document classifier is not?

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/document_classifier.mdx
# Usage

- To initialize the node, run:
- Alternatively.. -> this here needs to be explained I think, I don't think an NLP novice knows what zero-shot classification is;

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/entity_extractor.mdx
>  The `EntityExtractor` node extracts predefined entities out of a piece of text.
We didn't use code formatting for the names of other nodes, so it should be removed here as well for consistency

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/entity_extractor.mdx
>  The most common kind of entity extraction is Named Entity Extraction (NER) but
I don't think this is needed. It looks like we can use it for any type of entity extraction so I think we can get rid of this sentence altogether

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/entity_extractor.mdx
# Usage

- To initialize EntityExtractor, run the following code. You can provide any token classification model from the Hugging Face model hub as a model name.
- To run EntityExtractor as a standalone node, use the extract() method:
The return format...
- To run EntityExtractor in a query pipeline, run the following code. Entity extraction occurs on retrieved documents only and the extracted entities populate Document.meta..
- To run EntityExtractor in an indexing pipeline, run the following code. All documents in the document store have extracted entities as part of their metadata.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/route_documents.mdx
> +The `RouteDocuments` Node is a decision Node that makes it possible to route documents
remove the code formatting around the node name for consistency

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/route_documents.mdx
> +to different branches of your Pipeline based on their `content_type` or a metadata field.
Use this node to route documents to different branches of your pipeline based on their content_type or metadata field. RouteDocuments is a decision node.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/route_documents.mdx
> +By default `RouteDocuments` routes Documents based on content type (e.g. text vs table).
- To initialize RouteDocuments so that it routes documents based on their content type (text vs. table), run:
- To initialize RouteDocuments so that it routes documents based on a metadata field, run: (add comments to code and explanation of possible arguments)
- To initialize RouteDocuments as part of a pipeline, run: (we're missing this one)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/join_documents.mdx
> +
this needs more explanation

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/join_answers.mdx
> +The `JoinAnswers` node takes Answers from two or more Reader or Generator nodes and joins them to produce a single list of answers.
Remove the code formatting of the node name (consistency)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/join_answers.mdx
> +Initialize the node like this:
- To initialize the node, run:

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/join_answers.mdx
> +join_answers = JoinAnswers(
don't they need to import it before they can run it?

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/join_answers.mdx
> +- `concatenate` combines documents from multiple readers
formatting: `concatenate`: Combines (capital C)..
`merge`: Aggregates..

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/join_answers.mdx
> +You will need set `sort_by_score=False` to join these with Answers coming from other sources.
missing "to" after "need"

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/docs2answers.mdx
> +This Node is used to convert retrieved documents into predicted answers format.
This node converts retrieved documents..

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/docs2answers.mdx
> +It is useful for situations where you are calling a Retriever only pipeline via REST API.
You can use it to call a Retriever-only pipeline using REST API.

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/docs2answers.mdx
> +
So again, this needs more explanation (code comments) and also how to initialize it, how to run it on its own (if possible), how to run it in a pipeline (it's here)

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +# Pipeline Nodes
I think this needs to be renamed to something like About Nodes, because we'd need overview topics for other sections as well so we need to make sure the title is specific. Or Introduction to Nodes, or Nodes Overview?

2022-04-26 08:27 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +If you'd like to define our own, you'll need to create a class that looks something like this:
I think this part doesn't belong here. It's a general topic about nodes, telling people how to create a custom node here is too early. I think we should have a topic "Custom nodes" or "Creating custom nodes" and a subsection for creating custom decision nodes there

2022-04-26 08:29 UTC, agnieszka-m requested changes
I think it's much more useful now with the table at the beginning that lets you quickly check how to use the node. One thing I have a problem with is the Usage section, I'm not sure it belongs here or to the API? if it belongs here then we'll need to explain all the arguments here as well. I think we should also ask Tuana about this, maybe she'll have some thoughts.

2022-05-02 15:46 UTC, brandenchan commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +doc = converter.convert(file_path=file, meta=None)
unfortunately we can't because the processor doesn't take file paths as input

2022-05-02 16:01 UTC, brandenchan commented on docs/latest/pipeline_nodes/preprocessor.mdx
> +## Document Format
It's a bit complicated and I would vote against it. the input isn't just any plain dictionary, its a dictionary in this very particular format.

2022-05-02 16:04 UTC, brandenchan commented on docs/latest/pipeline_nodes/file_converters.mdx
> +|__Input__       | Files                                                                                                                                                                  |
It's a bit tricky because in Haystack it is a filename string but in DC it is an actual file you upload right? Gonna just change it to Filename here

2022-05-02 16:20 UTC, brandenchan commented on docs/latest/pipeline_nodes/retriever.mdx
I think that the classes row in the table will give an overview of what there is. Later in the file, there is section for each

2022-05-03 08:07 UTC, brandenchan commented on docs/latest/pipeline_nodes/generator.mdx
I thought that we were always full stopping lists and bullet points? Or does it depend on whether each item is a single sentence or not?

2022-05-03 08:44 UTC, brandenchan commented on docs/latest/pipeline_nodes/entity_extractor.mdx
>  The most common kind of entity extraction is Named Entity Extraction (NER) but
Truth is, there isn't really any other commonly used type of Entity Extraction. NER is probably more widely known than Entity Extraction

2022-05-03 09:02 UTC, merged