Change Default from GraphDB to InMemory Knowledge Graph
deepset-ai/haystack-website pull request #350
Opened 2022-06-27 09:40 UTC by brandenchan

Addresses #346

2022-06-27 09:41 UTC, brandenchan commented
@julian-risch Could you confirm whether the section about name spaces is also relevant to InMemoryKnowledgeGraph?

2022-06-28 08:36 UTC, julian-risch requested changes
Thanks for picking this up so quickly! I left to comments with requests for changes. Everything else looks very good to me already! 👍

2022-06-28 08:36 UTC, julian-risch commented on docs/latest/guides/knowledge_graph.mdx
> +Indices can be deleted and created with `InMemoryKnowledgeGraph.delete_index()` and `InMemoryKnowledgeGraph.create_index(config_path)`.
`create_index()` doesn't have a `config_path` but only an optional `index` parameter (just as the `delete_index()` method). I would leave out the parameter of `create_index()` here.

2022-06-28 08:36 UTC, julian-risch commented on docs/latest/guides/knowledge_graph.mdx
> +To allow the use of abbreviations of namespaces, GraphDBKnowledgeGraph needs to know about them:
Maybe we could emphasize here that setting prefixes explicitly is only necessary with `GraphDBKnowledgeGraph` but not with `InMemoryKnowledgeGraph`. The latter imports them automatically from the ttl file. I'd say that the tutorial notebook also could be clearer on this topic.

2022-07-01 08:17 UTC, merged