Add Indexing Pipeline Information
deepset-ai/haystack-website pull request #360
Opened 2022-07-07 15:49 UTC by brandenchan

2022-07-07 15:52 UTC, mkkuemmel commented on docs/latest/components/pipelines.mdx
> +The first Node in an indexing pipeline will usually be a [File Convertor](/pipeline_nodes/file_converters) or a FileTypeClassifier and take "File" as its input.
Typo: File Converter

2022-07-07 15:57 UTC, mkkuemmel commented
Great explanation, much easier to understand than before I think

2022-07-08 07:27 UTC, agnieszka-m requested changes
Please remember about the style - no future tense, passive, etc. When in doubt, check out the [Writing Guidelines](https://www.notion.so/deepsetai/Writing-Guidelines-8757f789892349e4840845e3d72ec993) :)

2022-07-08 07:27 UTC, agnieszka-m commented on docs/latest/components/pipelines.mdx
> +Indexing pipelines take files as input. They convert them into Haystack Documents and perform some processing steps. Then they index the Documents into a Document Store.
Can we first add some introductory info, like: Indexing pipelines prepare your files for search. Their main objective is to convert your files into Haystack Documents, which are passages of raw text stored in a Document Store (here a link to the Document in glossary?). Indexing pipelines can also preprocess the files by.. (can we add an example here? if not, let's remove the info about processing).

2022-07-08 07:27 UTC, agnieszka-m commented on docs/latest/components/pipelines.mdx
> +The first Node in an indexing pipeline will usually be a [File Converter](/pipeline_nodes/file_converters) or a FileTypeClassifier and take "File" as its input.
How about adding some more info about what these nodes can do: 
Depending on the file types you have, you can use [FileTypeClassifier](/reference/file-classifier) as the first node in your pipeline. It routes your files to appropriate [File Converters)(/pipeline_nodes/file_converters), which then extract text from your files and cast it into Documents.

2022-07-08 07:27 UTC, agnieszka-m commented on docs/latest/components/pipelines.mdx
> +The last Node will always be a Document Store.
```suggestion
The last Node is always a Document Store.
```

2022-07-08 07:27 UTC, agnieszka-m commented on docs/latest/components/pipelines.mdx
> +Here's an example of an indexing pipeline that preprocesses and classifies each document:
Are there any other nodes in between? Preprocessor?

2022-07-08 07:27 UTC, agnieszka-m commented on docs/latest/components/pipelines.mdx
> +**Tutorial:** have a look at the [Document Classification at Indexing Tutorial](/tutorials/doc-class-index) for a more detailed example of this kind of pipeline.
```suggestion
**Tutorial:** For a more detailed example of an indexing pipeline, have a look at the [Document Classification at Indexing Tutorial](/tutorials/doc-class-index).
```

2022-07-08 07:27 UTC, agnieszka-m commented on docs/latest/components/pipelines.mdx
> +The first Node in a querying pipeline will take "Query" as its input and the documents will most often be found within the Retriever which in turn contains a Document Store.
This is a bit unclear. Can we simplify it? Does a query pipeline always have a retriever? 
Maybe we can say something like: The first node in a querying pipeline always takes query as input. To find the right answer, the piepline uses documents stored in a document store.

2022-07-08 07:27 UTC, agnieszka-m commented on docs/latest/components/pipelines.mdx
> +A querying pipeline for Open-Domain QA might look something like this:
Here's an example of what a querying pipeline for open-domain question answering may look like:

2022-07-08 07:27 UTC, agnieszka-m commented on docs/latest/components/pipelines.mdx
> +For query pipelines, you will need to provide `query` as an argument:
```suggestion
For querying pipelines, provide `query` as an argument:
```

2022-07-08 07:27 UTC, agnieszka-m commented on docs/latest/components/pipelines.mdx
> +For query pipelines, you will need to provide `query` as an argument:
If we're using "querying pipelines", let's be consistent throughout the docs.

2022-07-08 07:27 UTC, agnieszka-m commented on docs/latest/components/pipelines.mdx
> +For indexing pipelines, you will need to provide `file_paths` as an argument:
```suggestion
For indexing pipelines, provide `file_paths` as an argument:
```

2022-07-08 09:37 UTC, agnieszka-m requested changes
I think the file classifier info should be in a separate PR.

2022-07-08 09:37 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_classifier.mdx
> +A File Classifier distinguishes between text, pdf, markdown, docx and html files so that they can be appropriately routed through an indexing pipeline.
```suggestion
A File Classifier distinguishes between text, pdf, Markdown, Docx, and HTML files so that they can be appropriately routed through an indexing pipeline.
```

2022-07-08 09:37 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_classifier.mdx
> +A File Classifier distinguishes between text, pdf, markdown, docx and html files so that they can be appropriately routed through an indexing pipeline.
Does it also route the files? If yes, can we say: ...and HTML files and routes them to appropriate Nodes in an indexing pipeline.

2022-07-08 09:37 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_classifier.mdx
> +|__Input__       | Filename                                                                                                                                                                  |
If "filename" is not an object or class in Haystack, can we change it to File name?

2022-07-08 09:37 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_classifier.mdx
> +|__Output__      | Filename (routed)                                                                                                             |
same as above

2022-07-08 09:37 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_classifier.mdx
> +By default, the FileTypeClassifier has 5 outgoing edges. An incoming file will be routed through one of these outgoing edges.
```suggestion
By default, the FileTypeClassifier has five outgoing edges. It routes an incoming file through one of these outgoing edges.
```

2022-07-08 09:37 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_classifier.mdx
> +By default, the FileTypeClassifier has 5 outgoing edges. An incoming file will be routed through one of these outgoing edges.
Or actually, can we change this to (assuming I understood correctly and it's true):
By default, the FileTypeClassifier has five outgoing edges. It routes an incoming file through one of these outgoing edges to the [File Converter](/pipeline_nodes/file-converters), which then converts them into [Documents](/components/documents-ansers-labels#documents).

2022-07-08 09:37 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_classifier.mdx
> +
These are the default outgoing edges of the File Classifier:

2022-07-08 09:37 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/file_classifier.mdx
> +To set up a FileTypeClassifier, run:
Does "set up" mean "initialize"?

2022-07-08 09:37 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/overview.mdx
> +| [FileClassifier](/pipeline_nodes/file-classifier)      | FileTypeClassifier | Distinguishes between text, PDF, markdown, DOCX and HTML files |
```suggestion
| [FileClassifier](/pipeline_nodes/file-classifier)      | FileTypeClassifier | Distinguishes between text, PDF, Markdown, Docx, and HTML files |
```

2022-07-08 09:56 UTC, merged