Add early stopping section
deepset-ai/haystack-website pull request #386
Opened 2022-08-22 13:02 UTC by brandenchan

Add a section describing early stopping with code example.

2022-08-22 13:06 UTC, sjrl commented on docs/latest/pipeline_nodes/reader.mdx
> +To go for this approach, run:
I would suggest changing this to `To use this approach, run:`

2022-08-22 13:07 UTC, sjrl commented on docs/latest/pipeline_nodes/reader.mdx
> +from haystack.modeling.training.base import EarlyStopping
I would update this import to `from haystack.utils.early_stopping import EarlyStopping`

2022-08-22 13:08 UTC, sjrl commented on docs/latest/pipeline_nodes/reader.mdx
> +        metric='top_n_accuracy',
Consider updating the spacing to use 4 spaces to match the formatting of the code used earlier in this doc.

2022-08-22 13:49 UTC, sjrl commented on docs/latest/pipeline_nodes/reader.mdx
> +        data_dir='./data',
Update indents here as well please :)

2022-08-22 13:51 UTC, sjrl approved these changes
Looks good! Thanks for adding this :)

2022-08-23 07:30 UTC, agnieszka-m requested changes

2022-08-23 07:30 UTC, agnieszka-m commented on docs/latest/pipeline_nodes/reader.mdx
> +This performs cycles of training and evaluation until the model is no longer improving.
```suggestion
This method performs cycles of training and evaluation until the model is no longer improving.
```

2022-08-23 07:49 UTC, sjrl commented on docs/latest/pipeline_nodes/reader.mdx
> +This performs cycles of training and evaluation until the model is no longer improving.
Thanks for the change! And my apologies for approving the commit @brandenchan. I thought this was the PR in Haystack and not for the website.

2022-08-24 08:01 UTC, merged